name: quackacademy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  firebase_auth: ^4.20.0  # Updated to the latest stable version
  firebase_core: ^2.32.0  # Compatible version
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.15.0
  shared_preferences: ^2.0.15
  flame: ^1.25.0
  image_picker: ^0.8.7+3
  flutter_riverpod: ^2.3.6
  lottie: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/duck_logo.png
    - assets/images/Home.png
    - assets/images/Courses.png
    - assets/images/Leaderboard.png
    - assets/images/Profile.png
    - assets/images/html.png
    - assets/images/css.png
    - assets/images/js.png
    - assets/images/java.png
    - assets/images/python.png
    - assets/images/Cplus.png
    - assets/images/certificate.png
    - assets/images/Userprofile.png
    - assets/images/settings.png
    - assets/images/Lock.png
    - assets/images/Student1.png
    - assets/images/Student2.png
    - assets/images/Student3.png
    - assets/images/Student4.png
    - assets/images/flowchart1.png
    - assets/images/flowchart2.png
    - assets/images/flowchart3.png
    - assets/images/flowchart4.png
    - assets/images/datatype1.png
    - assets/images/datatype2.png
    - assets/images/javaicon1.png
    - assets/images/javaicon2.png
    - assets/images/
    - "assets/images/game_assets/BG1(440x246).png"
    - "assets/images/game_assets/BG2(440x246).png"
    - "assets/images/game_assets/BG3(440x246).png"
    - "assets/images/game_assets/BG4(440x246).png"
    - "assets/images/game_assets/BG5(440x246).png"
    - "assets/images/game_assets/BG6(440x246).png"
    - "assets/images/game_assets/duck(15FPS).png"
    - "assets/images/game_assets/Finish Line Layer.png"
    - "assets/images/game_assets/Start Line Layer.png"
    - assets/images/duckfavicon.png
    - assets/images/iconduck.png
    - "assets/images/Lottie/Animation - 1743523201612.json"

  fonts:
    - family: Jaro
      fonts:
        - asset: fonts/Jaro-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/duckfavicon.png"
